### ISSUE TITLE
2021.5.5 not working [BUG]

### ISSUE THREAD

**Issue by jasonwragg** [Pyhass/Hive-Custom-Component#105]
**Describe the bug**
Component stops working after upgrading to 2021.5.5

2021-06-21 09:21:35 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@xxxxxx.co.uk for hive
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/home/homeassistant/.homeassistant/custom_components/hive/__init__.py", line 75, in async_setup_entry
devices = await hive.session.startSession(hive_config)
File "/srv/homeassistant/lib/python3.8/site-packages/apyhiveapi/session.py", line 391, in startSession
await self.getDevices("No_ID")
File "/srv/homeassistant/lib/python3.8/site-packages/apyhiveapi/session.py", line 316, in getDevices
await self.hiveRefreshTokens()
File "/srv/homeassistant/lib/python3.8/site-packages/apyhiveapi/session.py", line 249, in hiveRefreshTokens
result = await self.auth.refreshToken(
AttributeError: 'NoneType' object has no attribute 'refreshToken'

**To Reproduce**
Steps to reproduce the behaviour:

1. Upgrade to the latest version in HACS
2. component stops working

**Additional context**
Downgrading to 2021.5.4 fixes the issue.
I don't have 2FA enabled.
