### ISSUE TITLE
[BUG] Error while setting up hive platform for binary_sensor: 'ConfigEntry' object has no attribute 'runtime_data'

### ISSUE THREAD

**Issue by Johnyb62** [Pyhass/Hive-Custom-Component#179]
Just updated HA to 2025.6.0 &new version of Hive (2025.6.1) became available so updated. 
Now lost access to all my hive devices. 

Looks like a different error from that previously posted. Let me know if need anything else.  Thanks 

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:382
integration: Binary sensor
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Error while setting up hive platform for binary_sensor: 'ConfigEntry' object has no attribute 'runtime_data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/hive/binary_sensor.py", line 76, in async_setup_entry
    hive = entry.runtime_data
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'


Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:382
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Error while setting up hive platform for climate: 'ConfigEntry' object has no attribute 'runtime_data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/hive/climate.py", line 61, in async_setup_entry
    hive = entry.runtime_data
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'


Logger: homeassistant.components.light
Source: helpers/entity_platform.py:382
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Error while setting up hive platform for light: 'ConfigEntry' object has no attribute 'runtime_data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/hive/light.py", line 36, in async_setup_entry
    hive = entry.runtime_data
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'



Logger: homeassistant.helpers.frame
Source: helpers/frame.py:335
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Detected that custom integration 'hive' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('hive', '935ba53d-163b-4677-958f-bb37af4edf53'), with device info: {'identifiers': {('hive', '9c913dfb-c89b-462b-b177-a15ad46dec06')}, 'manufacturer': 'Computime', 'model': 'SLT2', 'name': 'Thermostat', 'sw_version': '06005300', 'via_device': ('hive', '935ba53d-163b-4677-958f-bb37af4edf53')} at custom_components/hive/sensor.py, line 97: async_add_entities(entities, True). This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/Pyhass/Hive-Custom-Component/issues


Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:382
integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Error while setting up hive platform for switch: 'ConfigEntry' object has no attribute 'runtime_data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/hive/switch.py", line 41, in async_setup_entry
    hive = entry.runtime_data
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'


Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:382
integration: Water heater ([documentation](https://www.home-assistant.io/integrations/water_heater), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+water_heater%22))
First occurred: 12:58:14 PM (1 occurrence)
Last logged: 12:58:14 PM

Error while setting up hive platform for water_heater: 'ConfigEntry' object has no attribute 'runtime_data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/hive/water_heater.py", line 52, in async_setup_entry
    hive = entry.runtime_data
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'





```
