### ISSUE TITLE
[BUG] Failed to setup HA core 2025.6.0

### ISSUE THREAD

**Issue by virtusas** [Pyhass/Hive-Custom-Component#176]
Since yesterday evening Hive stopped working. With error failed to setup. The only change was Core updated to 2025.6.0

Here is log:

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 06:35:26 (1 occurrence)
Last logged: 06:35:26

Error setting up entry *********@gmail.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hive/__init__.py", line 100, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, ha_type)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by 3shirts** [comment]
Yep, same issue. Stopped working when my HA container updated.

**Comment by snipsey** [comment]
Same issue - slightly different error message

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hive/__init__.py", line 100, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, ha_type)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by cstosgale** [comment]
Looks like this could be a simple fix:

https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by Stealth100** [comment]
Also have same issue since update to 2025.6.0 looking for a fix please

**Comment by Stealth100** [comment]
> I've submitted a PR to fix this issue here: [#177](https://github.com/Pyhass/Hive-Custom-Component/pull/177)
> 
> I've confirmed this has resolved the issue for me. We just need a maintainer to merge this PR and we should be good to go! You can also make the changes described in that PR manually on your HA instance by modifying /custom_components/hive/**init**.py


Ok great thanks, I'm fairly new with HA. do i just need to replace

hass.config_entries.async_forward_entry_setup

With

hass.config_entries.async_forward_entry_setups

In init.py file?

**Comment by virtusas** [comment]
> Anyone else missing entities?, i used to have 12 just for the thermostat now 7 appear even after a re-install.
> 
> also nothing showing up as climate when setting up a card

Yeah the same for me. No climate.****** entities left.

**Comment by steverumsby** [comment]
> Anyone else missing entities?, i used to have 12 just for the thermostat now 7 appear even after a re-install.
> 
> also nothing showing up as climate when setting up a card

Yes, me also. I'm missing the controls for climate devices - thermostat and radiator valves - and also the controls for bulbs.

I'm reverting to HA 2025.5 for now, until this gets sorted out. I'm glad I have a "test" HA instance where I try upgrades first, before upgrading the live instance.

**Comment by snipsey** [comment]
Worked for me too - had to delete the previous Hive integration and delete the custom_components/hive folder, restarted and added added the integration back which had automatically detected.

**Comment by payneardo73** [comment]
Thanks for the updates, deleted and reinstalled and no ability to turn plugs on or off and thermostat as well

**Comment by Stealth100** [comment]
> Just to note, if you delete the custom components folder and don’t re-install this integration via HACS, you’ll end up on the built in Hive integration and miss out on the great additional features you get with this version!
> 
> You should only need to update, and worst case delete the configuration but not uninstall the integration.

I just tried re installing hacs version again, soon as I do i lose all entities?

**Comment by cstosgale** [comment]
Sorry, I've just realised there is an outstanding issue which is it doesn't appear to create any climate entities, only sensors.

**Comment by Stewbo1** [comment]
Thank you but I just updated and it's still "Failed to unload"

**Comment by Johnyb62** [comment]
Updated to V2025.6.2 but still have same issue (ie nothing working).
'ConfigEntry' object has no attribute 'runtime_data'
Think this is a new error:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:335
First occurred: 4:35:17 PM (1 occurrence)
Last logged: 4:35:17 PM

Detected that custom integration 'hive' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('hive', '935ba53d-163b-4677-958f-bb37af4edf53'), with device info: {'identifiers': {('hive', '9c913dfb-c89b-462b-b177-a15ad46dec06')}, 'manufacturer': 'Computime', 'model': 'SLT2', 'name': 'Thermostat', 'sw_version': '06005300', 'via_device': ('hive', '935ba53d-163b-4677-958f-bb37af4edf53')} at custom_components/hive/sensor.py, line 97: async_add_entities(entities, True). This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/Pyhass/Hive-Custom-Component/issues
```

BTW FYI noticed this just now.  When I look at the Hacs page it shows I've got 2025.6.2 installed, but on the integration page in HA it shows '2021.7.0'.   

<img width="286" alt="Image" src="https://github.com/user-attachments/assets/a0621f53-b0cf-457e-9c33-681a5ae8533d" />

<img width="219" alt="Image" src="https://github.com/user-attachments/assets/798d8a45-d76d-48f4-a312-32b59558b27a" />

**Comment by jasonwragg** [comment]
I've added a pull request to fix this.

**Comment by steverumsby** [comment]
> I’ve pushed out 2025.6.3 with [@jasonwragg](https://github.com/jasonwragg) fix.
> 
> Thanks for the PR 🤞

That seems to have done the trick. Thanks all. :-)

**Comment by craggus2000** [comment]
> I'm afraid I'm still having an issue, even though I've manually downloaded x2025.6.3 the integration page in HA it shows '2021.7.0'.
> 
> <img alt="Image" width="811" src="https://private-user-images.githubusercontent.com/34771175/462086548-d0325a7c-29f6-40f5-8118-b2513b30fc03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE1NzIyNzgsIm5iZiI6MTc1MTU3MTk3OCwicGF0aCI6Ii8zNDc3MTE3NS80NjIwODY1NDgtZDAzMjVhN2MtMjlmNi00MGY1LTgxMTgtYjI1MTNiMzBmYzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzAzVDE5NDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NDdkNTRjNGNiMzllODNhMmQyNTllZTUxNjFiYTI2ZGY0NTY5YTNkMTVmN2FjOTMwN2Y4MDRkYmE5NmEwN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dbL0UuU7PQ04GJL4ISko1BUTX1QE2jDo2oCqlSHoB5M">
> Also I'm getting the following error: Logger: homeassistant.config_entries Source: config_entries.py:749 First occurred: 15:43:18 (3 occurrences) Last logged: 15:53:58
> 
> Error setting up entry [peter.j.morgan@tq26rs.me](mailto:peter.j.morgan@tq26rs.me) for hive Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/apyhiveapi/api/hive_auth_async.py", line 548, in refresh_token result = await self.loop.run_in_executor( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<7 lines>... ) ^ File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/botocore/client.py", line 569, in _api_call return self._make_api_call(operation_name, kwargs) ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/botocore/client.py", line 1023, in _make_api_call raise error_class(parsed_response, operation_name) botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Invalid Refresh Token.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/hive/**init**.py", line 90, in async_setup_entry devices = await hive.session.startSession(hive_config) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/apyhiveapi/session.py", line 502, in startSession await self.getDevices("No_ID") File "/usr/local/lib/python3.13/site-packages/apyhiveapi/session.py", line 425, in getDevices await self.hiveRefreshTokens() File "/usr/local/lib/python3.13/site-packages/apyhiveapi/session.py", line 304, in hiveRefreshTokens result = await self.auth.refresh_token( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ self.tokens.tokenData["refreshToken"] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/apyhiveapi/api/hive_auth_async.py", line 562, in refresh_token raise HiveInvalid2FACode from err apyhiveapi.helper.hive_exceptions.HiveInvalid2FACode

I'm having this same issue

**Comment by pid20** [comment]
I have followed the instructions to download and replace the hive custom components files and I am getting the same error showing the wrong version 2021.7.0 and it still doesn't load, any fix for this or s there any alternative as I use this a lot

**Comment by pid20** [comment]
I have tried all the methods above and still no luck, if I roll back to the previous release the component works but doesn't create the climate entities, which I gather was a fix in the most recent release.
